# docker-compose -f docker-compose.sonar.yml up -d
# docker-compose -f docker-compose.sonar.yml down
version: '3'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - '9000:9000'
      - '9092:9092'