terminal:
  colorScheme:
    name: AdventureTime
    foreground: '#f8dcc0'
    background: '#1f1d45'
    cursor: '#efbf38'
    colors:
      - '#050404'
      - '#bd0013'
      - '#4ab118'
      - '#e7741e'
      - '#0f4ac6'
      - '#665993'
      - '#70a598'
      - '#f8dcc0'
      - '#4e7cbf'
      - '#fc5f5a'
      - '#9eff6e'
      - '#efc11a'
      - '#1997c6'
      - '#9b5953'
      - '#c8faf4'
      - '#f6f5fb'
  background: colorScheme
  ligatures: true
  cursor: beam
  environment: {}
  profile: powershell-core
  workingDirectory: C:\Users\eglove\Projects
  alwaysUseWorkingDirectory: true
  autoOpen: false
  searchOptions: {}
hotkeys:
  toggle-window: []
  shell: {}
  profile: {}
serial: {}
ssh: {}
appearance:
  tabsLocation: top
  theme: Standard
enableWelcomeTab: false
pluginBlacklist: []
version: 1
